name: lightsoff
adopt-info: lightsoff
summary: Turn off all the lights
description: |
  Lights Off is a collection of light switch puzzles. Clicking on a light
  toggles it either on or off, but also toggles all the surrounding lights,
  too. Your objective is simple: turn off all the lights!

  Players who delight in turning off lights will enjoy the huge number of
  levels.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-2.0+
  title: Lights Off

slots:
  # for GtkApplication registration
  lightsoff:
    interface: dbus
    bus: session
    name: org.gnome.LightsOff

apps:
  lightsoff:
    command: usr/bin/lightsoff
    extensions: [gnome]
    plugs:
      - gsettings
      - opengl
    desktop: usr/share/applications/org.gnome.LightsOff.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

parts:
  lightsoff:
    source: https://gitlab.gnome.org/GNOME/lightsoff.git
    source-type: git
    source-tag: '40.0.1'
    parse-info: [usr/share/metainfo/org.gnome.LightsOff.appdata.xml]
    override-build: |
      sed -i.bak -e 's|Icon=org.gnome.LightsOff$|Icon=${SNAP}/meta/gui/org.gnome.LightsOff.svg|g' $CRAFT_PART_SRC/data/org.gnome.LightsOff.desktop.in
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/hicolor/scalable/apps/org.gnome.LightsOff.svg $CRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
